// Class automatically generated by Dev-C++ New Class wizard

#ifndef KANGAROOLIST_H
#define KANGAROOLIST_H
#include "kangaroo.h"
#include "node.h"
/*
* No description
*/
class kangarooList
{
public:
	// class constructor
	kangarooList();
	// class destructor
	~kangarooList();
	
	
	virtual int size()=0; //entrega el largo de la lista
	virtual bool isEmpty()=0; //indica si la lista está vacía o no
	virtual void add(int position, kangaroo k)=0; //agrega un canguro k a la lista e n la posición position
	virtual kangaroo get(int position)=0; //devuelve el canguro de la posición position
	virtual void remove(int position)=0; //elimina el canguro de la posición position

};

#endif // KANGAROOLIST_H
