
// Class automatically generated by Dev-C++ New Class wizard
#include <sstream>
#include "kangaroo.h" // class's header file
using namespace std;
// class constructor
kangaroo::kangaroo()
{
	// insert your code here
}

kangaroo::kangaroo(double j, string n) : _jump(j), _name(n)
{
	
}

// class destructor
kangaroo::~kangaroo()
{
	// insert your code here
}

ostream& operator<< (ostream& out, const kangaroo& k)
{
         ostringstream os;
         double d = k._jump;
         os << d;
         string str = os.str();

         string respuesta = k._name + "\t" + str;
         out << respuesta;
         return out;
         
} 

string kangaroo::getName()
{
	return this->_name;
}

double kangaroo::getJump()
{
    return this->_jump;
}
