// Class automatically generated by Dev-C++ New Class wizard

#include "kangaroolist.h" // class's header file

// class constructor
kangarooList::kangarooList()
{
	// insert your code here
}

// class destructor
kangarooList::~kangarooList()
{
	// insert your code here
}
