// Class automatically generated by Dev-C++ New Class wizard

#ifndef KANGAROOARRAY_H
#define KANGAROOARRAY_H

/*
 * No description
 */
 #include "kangaroolist.h"
 #include "kangaroo.h"
 
class kangarooArray : public kangarooList
{
	public:
		// class constructor
		kangarooArray();
		kangarooArray(int max);
		kangarooArray(const kangarooArray &kSource);
	    kangarooArray& operator= (const kangarooArray &kSource);
		// class destructor
		virtual ~kangarooArray();
		
		//métodos
		virtual int size(); //entrega el largo de la lista
    	virtual bool isEmpty(); //indica si la lista está vacía o no
    	virtual void add(int position, kangaroo k); //agrega un canguro k a la lista en la posición position
    	virtual kangaroo get(int position); //devuelve el canguro de la posición position
    	virtual void remove(int position);//elimina el canguro de la posición position
		virtual void expandir();
		
		friend ostream& operator<< (ostream& out,const kangarooArray& k);
		
	private:
            kangaroo* _values;
            int _size;
            int _length;
                
};

#endif // KANGAROOARRAY_H
