// Class automatically generated by Dev-C++ New Class wizard

#ifndef KANGAROOLINKED_H
#define KANGAROOLINKED_H
#include "kangaroolist.h"
#include <iostream>
/*
* No description
*/
class kangarooLinked : public kangarooList{
private:
	node* _first;
	int _size;
	
public:
	// class constructor
	kangarooLinked();
	// class destructor
	~kangarooLinked();
	kangarooLinked(const kangarooLinked &kSource);
	kangarooLinked& operator= (const kangarooLinked &kSource);
	
	int size(); 
	bool isEmpty(); 
	void add(int position, kangaroo k);
	kangaroo get(int position); 
	void remove(int position);
	friend ostream& operator<< (ostream& out,const kangarooLinked& k); 


};

#endif // KANGAROOLINKED_H
