
// Class automatically generated by Dev-C++ New Class wizard

#ifndef KANGAROO_H
#define KANGAROO_H

/*
* No description
*/

#include <string>

using namespace std;

class kangaroo
{
private:
	double _jump;
	string _name;

public:
	friend ostream& operator<< (ostream& out,const kangaroo& k); 
	kangaroo();
	kangaroo(double j, string n);
	~kangaroo();
	string getName();
	double getJump();
	friend class kangarooList;
	
	
	

	

	
	
	
	
};

#endif // KANGAROO_H
