#include "kangaroo.h"
// Class automatically generated by Dev-C++ New Class wizard

#ifndef NODE_H
#define NODE_H

/*
* No description
*/
class node
{
private:
	kangaroo _data;
	node* _next;

public:
	// class constructor
	node(kangaroo k);
	// class destructor
	~node();
	kangaroo getData();
	node* getNext();

	void setNext(node *n);
	friend class kangarooList;
	
	
	
	
};

#endif // NODE_H
